name: Model Tuning Pipeline

on:
  push:
    paths:
      - 'Membangun_model/modelling_tuning.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  run-model-tuning:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r Membangun_model/requirements.txt

    - name: Run model tuning and log to DagsHub
      run: |
        python Membangun_model/modelling_tuning.py
