name: Run MLflow Tuning

on:
  push:
    paths:
      - 'Membangun_model/modelling_tuning.py'
      - '.github/workflows/mlflow-model.yml'
  workflow_dispatch:

jobs:
  run-modelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r Membangun_model/requirements.txt

    - name: Run MLflow tuning
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python Membangun_model/modelling_tuning.py

